index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login

checklist_create:
    path: /checklist/new
    controller: App\Controller\ChecklistCreateController::new

checklist_create_with_template:
    path: /checklist/new/{templateId}
    controller: App\Controller\ChecklistCreateController::new_with_template

checklist_create_done:
    path: /checklist/new/{checklistId}/done
    controller: App\Controller\ChecklistCreateController::done

checklist:
    path: /checklist/{checklistId}
    controller: App\Controller\SampleController::index

checklist_entry_update:
    path: /checklist/{checklistId}/updateEntry
    controller: App\Controller\SampleController::entry_update
    methods: POST
    defaults:
        _format: json


app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

pusher_authenticate:
    path: /auth
    controller: App\Controller\SecurityController::pusher_authenticate
