Website Onboarding:
  Accessibility general audit:
    - Colors & contrast
    - Responsive
    - Cognitive
    - Semantic HTML and/or ARIA
  Errors:
    - JavaScript Console
    - Redirects (301/302)
    - Missing pages (404/410)
    - Error pages (4xx/50x)
  Site speed reports:
    - https://tools.pingdom.com
    - https://www.webpagetest.org
    - https://developers.google.com/speed/pagespeed/insights/
  Performance metrics for key pages:
    - Page speed
    - Content type breakdown
    - Server settings (caching, compression
  Server settings:
    - Caching encouraged (ETag, expires, caching directives)
    - HTTP version
    - SSL/TLS
    - Server and component versions (OS, PHP, database, etc.)
  Analytics:
    - Current platform (none/GA/GTM/etc.)
    - Analysis and report of current traffic by interesting segments
  Site general information:
    - CMS with version
    - Server access (FTP, cPanel, SSH, etc.)
    - General module/plugin/library overview
    - Form platform(s) (Gravity/Webform/HubSpot/etc.)
  Hosting, Domains and DNS audit:
    - Where is site hosted
    - What domain names, including sub-domains, point to the site
    - Where is DNS hosted for each domain
    - Who has admin access to hosting, domain management and DNS
