Web Site Launch:
  Content:
    - Spelling, grammar, facts and formatting checked
    - All pages have titles
    - Page metadata setup
    - Images have appropriate alt text
    - Favicons setup
    - Search works as expected
  Analytics:
    - Google Analytics setup
    - GA/GTM installed
    - Goals in GA setup
  Contact methods accurate:
    - Phone numbers
    - Email addresses
    - Physical addresses
  Social/sharing accurate:
    - Facebook
    - LinkedIn
    - YouTube
    - Twitter
    - Flickr
    - Pinterest
    - Instagram
  Common pages exist:
    - Privacy Policy
    - Contact
    - Accessibility
  Error pages created and serving correctly:
    - 401 - Unauthorized
    - 403 - Forbidden
    - 404 - Not Found
    - 410 - Gone
  Forms:
    - Admin notification correct and working
    - User notification correct and working
    - Form FROM email address approved
    - CMS can send from approved email address to all known recipients (SPF/DKIM/etc.)
    - All forms have unique "thank you" pages
  Testing:
    - List of supported browsers determined by analytics and/or client
    - All primary browsers must match feature-to-feature and UI-to-UI across all devices
    - All legacy browsers must function as similiar as possible to primary with potentially degraded UI/UX
    - Responsive testing for primary browsers is complete
    - Mobile testing for primary browsers is complete
  CSS/JS building:
    - Build script and tools are setup including yarn, npm, node, webpack
    - Polyfills for JS loaded
    - All JS files listed for build in the correct order
    - All CSS files listed for build in the correct order
  Performance:
    - All pages use W3C compliant HTML and CSS
    - All images optimized
    - CSS minified, aggregated and compressed
    - JS minified, aggregated and compressed
    - All pages have very low HTTP request count
    - All pages with assets have very low byte size
    - Page speed audit run on major pages
    - External assets avoided including fonts, JS, CSS, images, iframes
    - No console errors
  Security:
    - TLS cert for local termination setup
    - Local cert auto-renew setup and tested
    - Cloudflare TLS termination setup
  Hosting:
    - Hosting platform setup
    - Hosting configuration updated and modern
    - Server timezone correct
    - Redis setup
  Domains/DNS:
    - Canonical fully-qualified domain name chosen
    - Vanity and/or subdomain redirects in place
    - Private DNS issues investigated with client
  Email:
    - Server is able to send email in general
    - Server can send administrative emails
    - Server has a valid hostname for email
    - Web application has an SMTP override
    - SPF records are in place
    - DKIM records are in place
    - DMARC records are in place
  CMS:
    - All plugins/modules updated
    - All core updates applied
  WordPress:
    - Site Title and Tagline accurate
    - Timezone correct
    - "Plugin installed: Better WordPress Minify"
    - "Plugin installed: Classic Editor"
    - "Plugin installed: Relevanssi"
    - "Plugin installed: Redis"
    - "Plugin installed: Stream"
    - "Plugin installed: Yoast"
